ROOT := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
.DEFAULT_GOAL := verify

TOOLS := $(ROOT)/tools
OUT := $(ROOT)/out
GEN := $(OUT)/generated
ASM_GEN := $(GEN)/asm
BOUNDARIES := $(ROOT)/layout.tsv
BUILD_INPUTS_STAMP := $(GEN)/build_inputs.stamp

TARGET := $(ROOT)/kh2.elf
TMP_LINK_ELF := $(OUT)/linked.tmp.elf
FAST_LINK_ELF := $(OUT)/linked.fast.tmp.elf
TMP_LD := $(GEN)/kh2.temp.ld
LINK_RSP := $(OUT)/link.rsp
SLPM := $(ROOT)/SLPM_666.75

MAKE_JOBS ?= $(shell nproc 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1)
KH2_PS2_IMAGE ?= kh2-local/ps2-compiler:3.2-ee-040921-objdiff
# Native (docker-less) build: KH2_NATIVE=1 PS2_TOOLCHAIN=/path/to/extracted/gcc make
# PS2_TOOLCHAIN must contain bin/ee-g++ etc. (with a working interpreter) and
# a shim/ dir with as/ld symlinks to ee-as/ee-ld. See docs/native-toolchain.md.
KH2_NATIVE ?= 0
PS2_TOOLCHAIN ?= /opt/ps2/gcc
export KH2_NATIVE PS2_TOOLCHAIN
ifeq ($(KH2_NATIVE),1)
export PATH := $(PS2_TOOLCHAIN)/shim:$(KH2_OBJDIFF_DIR):$(PATH)
endif

PS2_PREP := $(ROOT)/docker/ps2/prepare.sh

CXXFLAGS := -O2 -g0 -x c++ -fno-exceptions -fno-rtti -fpermissive -ffunction-sections
ASFLAGS := -G0
VERIFY_AUTODIFF_COUNT ?= 3
VERIFY_SMALL_DIFF_MAX ?= 32

DOCKER_RUN_PS2 = docker run --rm \
	--platform linux/amd64 \
	-u "$$(id -u):$$(id -g)" \
	-v "$(ROOT):/work" \
	-v "/tmp:/tmp" \
	-w /work \
	"$(KH2_PS2_IMAGE)"

SLPM_MISSING_MSG := error: missing $(SLPM). Put SLPM_666.75 at repo root.
OBJDIFF_CONFIG_PATH := $(ROOT)/objdiff.json

define require_slpm
@test -f $(SLPM) || (echo "$(SLPM_MISSING_MSG)" >&2; exit 1)
endef

.PHONY: all build verify clean distclean preflight ps2-docker toolchain-check \
        regen-layout progress inner-all objdiff-config objdiff-report FORCE

all: build

build: $(TARGET) $(OBJDIFF_CONFIG_PATH)
	@python3 $(TOOLS)/objdiff.py progress --elf $(TARGET) --skip-report

$(SLPM):
	@echo "$(SLPM_MISSING_MSG)" >&2
	@exit 1

preflight: $(SLPM)
	@$(PS2_PREP)

ps2-docker:
	@$(ROOT)/docker/ps2/prepare.sh --build

# This include is generated by tools/build_elf.py.
ifneq ($(filter clean distclean ps2-docker toolchain-check,$(MAKECMDGOALS)),)
else
-include $(GEN)/objects.mk
endif

$(BOUNDARIES):
	@echo "error: missing $(BOUNDARIES)" >&2
	@exit 1

$(GEN)/objects.mk $(GEN)/layout_status.tsv $(GEN)/symbols.ld: $(BOUNDARIES) $(ROOT)/functions.tsv $(TOOLS)/build_elf.py $(TOOLS)/common.py
	@mkdir -p $(GEN)
	@python3 $(TOOLS)/build_elf.py objects

$(BUILD_INPUTS_STAMP): FORCE $(TOOLS)/build_elf.py
	@mkdir -p $(GEN)
	@python3 $(TOOLS)/build_elf.py inputs-stamp --out $@

regen-layout: $(GEN)/objects.mk

$(TMP_LD): $(ROOT)/kh2.ld $(GEN)/cxx_sections.ld
	@mkdir -p $(GEN)
	@sed -e '/\/\* @CXX_SECTIONS@ \*\//r $(GEN)/cxx_sections.ld' \
	     -e '/\/\* @CXX_SECTIONS@ \*\//d' $(ROOT)/kh2.ld > $@

$(TARGET): $(SLPM) $(BOUNDARIES) $(GEN)/objects.mk $(GEN)/layout_status.tsv $(GEN)/symbols.ld $(ROOT)/functions.tsv $(ROOT)/kh2.ld \
           $(TOOLS)/build_elf.py $(TOOLS)/common.py $(BUILD_INPUTS_STAMP)
ifeq ($(KH2_NATIVE),1)
	@$(MAKE) --no-print-directory -j"$(MAKE_JOBS)" inner-all
else
	@$(PS2_PREP)
	@$(DOCKER_RUN_PS2) bash -lc '/usr/bin/make -j"$(MAKE_JOBS)" inner-all'
endif
	@echo "Built $@"

$(OBJDIFF_CONFIG_PATH): $(TARGET) $(BOUNDARIES) $(GEN)/objects.mk $(GEN)/layout_status.tsv $(GEN)/symbols.ld $(ROOT)/functions.tsv $(TOOLS)/objdiff.py $(TOOLS)/common.py
	@python3 $(TOOLS)/objdiff.py config --elf $(TARGET)

inner-all: $(GEN)/objects.mk $(ORDERED_OBJS)
	@python3 $(TOOLS)/build_elf.py link-sections
	$(file >$(LINK_RSP),INPUT ( $(ORDERED_OBJS) ))
	@if ! python3 $(TOOLS)/build_elf.py fast-link --linked-elf $(FAST_LINK_ELF) --out-elf $(TARGET) --full-linked-elf $(TMP_LINK_ELF); then \
		sed -e '/\/\* @CXX_SECTIONS@ \*\//r $(GEN)/cxx_sections.ld' \
		    -e '/\/\* @CXX_SECTIONS@ \*\//d' $(ROOT)/kh2.ld > $(TMP_LD); \
		$(PS2_TOOLCHAIN)/bin/ee-ld --no-check-sections -T $(TMP_LD) -T $(LINK_RSP) -o $(TMP_LINK_ELF) -L$(PS2_TOOLCHAIN)/lib/gcc-lib/ee/3.2-ee-040921 -lgcc; \
		python3 $(TOOLS)/build_elf.py normalize --linked-elf $(TMP_LINK_ELF) --out-elf $(TARGET); \
	fi

out/build/%.o: %.cpp
	@mkdir -p $(dir $@)
	@$(PS2_TOOLCHAIN)/bin/ee-g++ $(CXXFLAGS) -c -o $@ $<

out/build/%.o: %.s
	@mkdir -p $(dir $@)
	@$(PS2_TOOLCHAIN)/bin/ee-as $(ASFLAGS) -o $@ $<

out/build/%.o: %.S
	@mkdir -p $(dir $@)
	@$(PS2_TOOLCHAIN)/bin/ee-as $(ASFLAGS) -o $@ $<

out/generated/asm/%.o: out/generated/asm/%.s
	@mkdir -p $(dir $@)
	@$(PS2_TOOLCHAIN)/bin/ee-as $(ASFLAGS) -o $@ $<
	@$(PS2_TOOLCHAIN)/bin/ee-objcopy -R .text -R .data -R .bss $@

.PRECIOUS: out/build/%.o out/generated/asm/%.o $(OBJDIFF_CONFIG_PATH)

verify: $(TARGET) $(BOUNDARIES) $(OBJDIFF_CONFIG_PATH)
	@python3 $(TOOLS)/objdiff.py verify $(SLPM) $(TARGET)

progress: $(BOUNDARIES)
	@{ \
		if [ ! -f "$(TARGET)" ]; then \
			$(MAKE) --no-print-directory build; \
		fi; \
	}
	@python3 $(TOOLS)/objdiff.py progress --elf $(TARGET)

objdiff-config: $(OBJDIFF_CONFIG_PATH)
	@{ \
		if [ ! -f "$(TARGET)" ]; then \
			$(MAKE) --no-print-directory build; \
		fi; \
	}

objdiff-report: $(OBJDIFF_CONFIG_PATH)
	@{ \
		if [ ! -f "$(TARGET)" ]; then \
			$(MAKE) --no-print-directory build; \
		fi; \
	}
	@python3 $(TOOLS)/objdiff.py report --elf $(TARGET)

clean:
	rm -rf $(OUT)/build
	rm -f $(TARGET) $(TMP_LINK_ELF) $(LINK_RSP) $(GEN)/objects.mk $(TMP_LD)
	@find $(ASM_GEN) -name '*.o' -delete 2>/dev/null || true

distclean: clean
	rm -rf $(OUT)
