// coverage: addr=0x00181570 symbol=_ZN2YS8PROGRESS11CheckAndSetEii size=92 class=branchy source=e3 status=exact fuzzy=100.0
// coverage-alternatives: m2c:near:94.5;ghidra:near:92.0;lift:near:91.6
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF





extern "C" u8 func_00181500(int) asm("func_00181500");
extern "C" void func_00181178(int) asm("func_00181178");

// E3 0x0048ff40 YS::PROGRESS::CheckAndSet -> PS2 0x00181570
u8 e3_00181570(int num, int cond) asm("_ZN2YS8PROGRESS11CheckAndSetEii");
u8 e3_00181570(int num, int cond)

{
  u8 bVar1;
  
  bVar1 = func_00181500(num);
  if ((!bVar1) && (bVar1 = func_00181500(cond), bVar1)) {
    func_00181178(num);
    return true;
  }
  return false;
}

