// coverage: addr=0x00192260 symbol=_ZN2YS7MESSAGE4ReadEii size=48 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: ghidra:exact:100.0;m2c:near:99.58;lift:near:27.0
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF




typedef u32 size_t;
extern "C" void * func_001921d8(int) asm("_ZN2YS7MESSAGE11GetFilenameEi");
extern "C" void func_00170518(void *, int, size_t) asm("_ZN2YS10CACHE_BUFF11ReadRequestEPKcij");

// E3 0x0044d1a8 YS::MESSAGE::Read -> PS2 0x00192260
void e3_00192260(int world, int pri) asm("_ZN2YS7MESSAGE4ReadEii");
void e3_00192260(int world, int pri)

{
  char *name;
  
  name = func_001921d8(world);
  func_00170518(name,pri,0);
  return;
}

