// coverage: addr=0x001ac700 symbol=_ZN2YS6WINDOW5closeEv size=40 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: lift:near:80.0;ghidra:near:80.0;m2c:near:80.0
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct YS_BITFLAG_1_u_int;
struct YS_MESSAGE_SIZE;
struct YS_MESSAGE_STYLE;
struct YS_MESSAGEDRAW;
struct YS_SLIST_ELEM_YS_WINDOW_1;
struct YS_WINDOW;

struct YS_BITFLAG_1_u_int {  // class YS::BITFLAG<1, u_int> size=0x4
    u8 Flag[4];   // raw: klass[1] (size mismatch)     // +0x0
};

struct YS_MESSAGE_SIZE {  // class YS::MESSAGE::SIZE size=0x8
    u32 Width;                                         // +0x0
    u32 Height;                                        // +0x4
};

struct YS_MESSAGE_STYLE {  // class YS::MESSAGE::STYLE size=0x18
    u32 Color;                                         // +0x0
    f32 Scale;                                         // +0x4
    f32 HScale;                                        // +0x8
    s32 LineSpace;                                     // +0xc
    u32 OrigColor;                                     // +0x10
    f32 OrigScale;                                     // +0x14
};

struct YS_MESSAGEDRAW {  // class YS::MESSAGEDRAW size=0x60
    YS_BITFLAG_1_u_int Flag;                           // +0x0
    void *Font;                                        // +0x4
    void *Message;                                     // +0x8
    void *Current;                                     // +0xc
    YS_MESSAGE_SIZE Size;                              // +0x10
    YS_WINDOW *Window;                                 // +0x18
    f32 Time;                                          // +0x1c
    s32 SelectNum;                                     // +0x20
    YS_MESSAGE_STYLE Style;                            // +0x24
    u32 Color;                                         // +0x3c
    u32 ShadowColor;                                   // +0x40
    s32 XPos;                                          // +0x44
    s32 YPos;                                          // +0x48
    f32 FadeTime;                                      // +0x4c
    YS_MESSAGE_SIZE MaxSize;                           // +0x50
    s32 Align;                                         // +0x58
    f32 FontTime;                                      // +0x5c
};

struct YS_SLIST_ELEM_YS_WINDOW_1 {  // class YS::SLIST_ELEM<YS::WINDOW, 1> size=0x4
    void *Next[1];                                     // +0x0
};

struct YS_WINDOW {  // class YS::WINDOW size=0x84
    void *_vptr_;                                      // +0x0
    s32 XPos;                                          // +0x4
    s32 YPos;                                          // +0x8
    YS_MESSAGEDRAW MessageDraw;                        // +0xc
    void *FontStyle;                                   // +0x6c
    s32 Phase;                                         // +0x70
    f32 Time;                                          // +0x74
    s32 Priority;                                      // +0x78
    YS_SLIST_ELEM_YS_WINDOW_1 SList;                   // +0x7c
    s32 MessageId;                                     // +0x80
};

#define PHASE_CLOSE (4)
extern "C" u8 func_001991a8(int, int) asm("func_001991a8");

// E3 0x004bc5f4 YS::WINDOW::close -> PS2 0x001ac700
void  e3_001ac700(YS_WINDOW *self) asm("_ZN2YS6WINDOW5closeEv");
void  e3_001ac700(YS_WINDOW *self)

{
  self->Phase = PHASE_CLOSE;
  func_001991a8(0x22,self->MessageId);
  return;
}

