// coverage: addr=0x001ac778 symbol=func_001ac778 size=20 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: corpus:near:93.0;lift:near:87.8;ghidra:near:87.8;m2c:near:87.6
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct YS_SLIST_YS_WINDOW_0;

struct YS_SLIST_YS_WINDOW_0 {  // class YS::SLIST<YS::WINDOW, 0> size=0x8
    void *Head;                                        // +0x0
    void *Tail;                                        // +0x4
};


extern "C" YS_SLIST_YS_WINDOW_0 D_01c6ced0 asm("D_01c6ced0");
extern "C" u32 e3g___LNst__ZN2YS5ARROW3setEiii_3 asm("E3_UNMAPPED_0072a094");
extern "C" u32 e3g___LNst__ZN2YS6WINDOW4InitEv_1 asm("E3_UNMAPPED_0072a0c4");
extern "C" u32 e3g___LNst__ZN2YS6WINDOW4InitEv_2 asm("E3_UNMAPPED_0072a0dc");
extern "C" u32 e3g___LNst__ZN2YS6WINDOW4InitEv_3 asm("E3_UNMAPPED_0072a0ec");

// E3 0x004bc62c YS::WINDOW::Init -> PS2 0x001ac778
void e3_001ac778() asm("func_001ac778");
void e3_001ac778()

{
  if (D_01c6ced0.Head != (void *)0x0) {




  }
  D_01c6ced0.Head = (void *)0x0;
  D_01c6ced0.Tail = (void *)0x0;
  return;
}

