// coverage: addr=0x001b1fc8 symbol=func_001b1fc8 size=40 class=branchy source=e3 status=exact fuzzy=100.0
// coverage-alternatives: ghidra:exact:100.0;m2c:near:81.5;lift:near:74.0
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF




#define PHASE_OK (0)
extern "C" s32 D_00350f18 asm("D_00350f18");
extern "C" int D_00350f1c asm("D_00350f1c");

// E3 0x00439410 YS::ITEMPIC::CanGetImageData -> PS2 0x001b1fc8
u8 e3_001b1fc8(int pic) asm("func_001b1fc8");
u8 e3_001b1fc8(int pic)

{
  u8 bVar1;
  
  bVar1 = false;
  if ((D_00350f18 == PHASE_OK) && (D_00350f1c == pic)) {
    bVar1 = true;
  }
  return bVar1;
}

