// coverage: addr=0x001de7d8 symbol=func_001de7d8 size=48 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: lift:near:94.92;ghidra:near:94.92;m2c:near:82.85
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct YS_SLIST_ryj_PAX_0;
struct ALLOCATOR;

struct YS_SLIST_ryj_PAX_0 {  // class YS::SLIST<ryj::PAX, 0> size=0x8
    void *Head;                                        // +0x0
    void *Tail;                                        // +0x4
};

struct ALLOCATOR {  // class ALLOCATOR size=0x4
    void *_vptr_;                                      // +0x0
};


extern "C" void func_001dcdb8(void *, int, int) asm("func_001dcdb8");
extern "C" void func_001de808() asm("func_001de808");
extern "C" ALLOCATOR * D_01d9e340 asm("D_01d9e340");
extern "C" YS_SLIST_ryj_PAX_0 D_01d9e348 asm("D_01d9e348");

// E3 0x002b6890 ryj::PAX::Init -> PS2 0x001de7d8
void e3_001de7d8(ALLOCATOR *allocator, int work_memory_size, int packet_memory_size) asm("func_001de7d8");
void e3_001de7d8(ALLOCATOR *allocator, int work_memory_size, int packet_memory_size)

{
  D_01d9e340 = allocator;
  func_001dcdb8(allocator,work_memory_size,packet_memory_size);
  D_01d9e348.Head = (void *)0x0;
  D_01d9e348.Tail = (void *)0x0;
  func_001de808();
  return;
}

