// coverage: addr=0x002421e8 symbol=func_002421e8 size=80 class=branchy source=e3 status=exact fuzzy=100.0
// coverage-alternatives: ghidra:near:50.25;m2c:near:35.65;lift:near:23.25
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct Tz_McSys;
struct ALLOCATOR;
struct SysDataKH2_HEADER;
struct SysDataKH2_DATA_anon_str_sysdata_kh2_h_43;
struct YS_BITFLAG_256_u_int;
struct YS_PROGRESS_FLAG;
struct SysDataKH2_DATA;
struct SysDataKH2;

struct Tz_McSys {  // class Tz::McSys size=0x8
    ALLOCATOR *m_Allocator;                            // +0x0
    s8 *m_DataBuff;                                    // +0x4
};

struct ALLOCATOR {  // class ALLOCATOR size=0x4
    void *_vptr_;                                      // +0x0
};

struct SysDataKH2_HEADER {  // structure SysDataKH2::HEADER size=0x10
    u32 Id;                                            // +0x0
    u16 Area;                                          // +0x4
    u16 Version;                                       // +0x6
    s8 Filler[8];                                      // +0x8
};

struct SysDataKH2_DATA_anon_str_sysdata_kh2_h_43 {  // structure SysDataKH2::DATA::__anon_str_sysdata_kh2_h_43 size=0x4
    u32 Filler : 31;                                   // +0x0
    u32 GameClear : 1;                                 // +0x4
};

struct YS_BITFLAG_256_u_int {  // class YS::BITFLAG<256, u_int> size=0x20
    u8 Flag[32];   // raw: klass[8] (size mismatch)    // +0x0
};

struct YS_PROGRESS_FLAG {  // class YS::PROGRESS::FLAG size=0x260
    YS_BITFLAG_256_u_int Flag[19];                     // +0x0
};

struct SysDataKH2_DATA {  // structure SysDataKH2::DATA size=0x264
    SysDataKH2_DATA_anon_str_sysdata_kh2_h_43 _bit;    // +0x0
    YS_PROGRESS_FLAG ProgressFlag;                     // +0x4
};

struct SysDataKH2 {  // class SysDataKH2 size=0x274
    SysDataKH2_HEADER Header;                          // +0x0
    SysDataKH2_DATA Data;                              // +0x10
};

typedef u32 u_int;
extern "C" u8 func_002efa40(u32) asm("func_002efa40");
extern "C" u_int D_0035ecb8 asm("D_0035ecb8");

// E3 0x003686c0 Tz::McSys::isGameClearKH2 -> PS2 0x002421e8
u8  e3_002421e8(Tz_McSys *self) asm("func_002421e8");
u8  e3_002421e8(Tz_McSys *self)

{
  u8 bVar1;
  u8 bVar2;
  
                    /* Unresolved local var: SysDataKH2 * sysdata@[???] */
  bVar2 = false;
  bVar1 = func_002efa40((SysDataKH2 *)ZEXT48(self->m_DataBuff));
  if ((bVar1) || ((D_0035ecb8 & 1) != 0)) {
    bVar2 = true;
  }
  return bVar2;
}

