// coverage: addr=0x00241740 symbol=func_00241740 size=44 class=branchy source=e3 status=exact fuzzy=100.0
// coverage-alternatives: ghidra:near:84.62;m2c:near:78.43;lift:near:9.09
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct Axa_anon_str_libmcR_h_121;
struct Tz_SaveFileInfo;
struct Tz_MCInfo;

struct Axa_anon_str_libmcR_h_121 {  // structure Axa::__anon_str_libmcR_h_121 size=0x8
    u16 Year;                                          // +0x0
    u8 Month;                                          // +0x2
    u8 Day;                                            // +0x3
    u8 Hour;                                           // +0x4
    u8 Min;                                            // +0x5
    u8 Sec;                                            // +0x6
    u8 Resv2;                                          // +0x7
};

struct Tz_SaveFileInfo {  // structure Tz::SaveFileInfo size=0x20
    s32 Stat;                                          // +0x0
    void *Place;                                       // +0x4
    u32 PlayTime;                                      // +0x8
    u32 Munnies;                                       // +0xc
    s8 GameLevel;                                      // +0x10
    s8 PlayerLevel;                                    // +0x11
    s8 World;                                          // +0x12
    s8 Face;                                           // +0x13
    s8 ChgWorldName;                                   // +0x14
    s8 Filler[3];                                      // +0x15
    Axa_anon_str_libmcR_h_121 SaveTime;                // +0x18
};

struct Tz_MCInfo {  // structure Tz::MCInfo size=0xc68
    s8 Slot;                                           // +0x0
    s8 Pos;                                            // +0x1
    s16 FreeSize;                                      // +0x2
    s8 isUnformat;                                     // +0x4
    s8 isFindSystem;                                   // +0x5
    s8 Filler[2];                                      // +0x6
    Tz_SaveFileInfo Info[99];                          // +0x8
};


extern "C" void func_00240c08(int, void *, int) asm("func_00240c08");
extern "C" Tz_MCInfo * D_0035ec94 asm("D_0035ec94");

// E3 0x0036bdf8 Tz::MCard::SetDataBuff2MCInfo -> PS2 0x00241740
void e3_00241740(int num) asm("func_00241740");
void e3_00241740(int num)

{
                    /* Unresolved local var: int idx@[???] */
  if (num < 0) {
    num = (int)*(char *)(ZEXT48(D_0035ec94) + 1);
  }
  func_00240c08(num,(void *)0x0,0x13);
  return;
}

