// coverage: addr=0x002954e0 symbol=_ZN2Tz10JmWorldSel11isWorldOpenEi size=36 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: corpus:near:90.0;lift:near:48.89;ghidra:near:48.89;m2c:near:48.89
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct Tz_JmWorldDataInfo;

struct Tz_JmWorldDataInfo {  // structure Tz::JmWorldDataInfo size=0x10
    s8 World;                                          // +0x0
    s8 ImgName[3];                                     // +0x1
    u16 DefName;                                       // +0x4
    u16 DefNameEv;                                     // +0x6
    u16 OpenProgress;                                  // +0x8
    u16 ChgName;                                       // +0xa
    u16 ChgNameEv;                                     // +0xc
    u16 ChgProgress;                                   // +0xe
};


extern "C" void * func_002953c8(int) asm("_ZN2Tz10JmWorldSel10GetId2InfoEi");
extern "C" u8 func_002941a8(void *) asm("_ZN2Tz6JmInfo11isWorldOpenEPKNS_15JmWorldDataInfoE");

// E3 0x003639e4 Tz::JmWorldSel::isWorldOpen -> PS2 0x002954e0
u8 e3_002954e0(int id) asm("_ZN2Tz10JmWorldSel11isWorldOpenEi");
u8 e3_002954e0(int id)

{
  Tz_JmWorldDataInfo *info;
  u8 bVar1;
  
  info = func_002953c8(id);
  bVar1 = func_002941a8(info);
  return bVar1;
}

