// coverage: addr=0x00293b70 symbol=_ZN2Tz9ChgMember18isExecChangeMemberEv size=44 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: ghidra:near:58.18;m2c:near:44.45;lift:link:0.0
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define CONCAT11(a,b) ((u16)(((u16)(u8)(a)<<8)|(u8)(b)))
#define CONCAT12(a,b) ((u32)(((u32)(u8)(a)<<16)|(u16)(b)))
#define CONCAT13(a,b) ((u32)(((u32)(u8)(a)<<24)|((u32)(b)&0xffffff)))
#define CONCAT14(a,b) ((u64)(((u64)(u8)(a)<<32)|(u32)(b)))
#define CONCAT21(a,b) ((u32)(((u32)(u16)(a)<<8)|(u8)(b)))
#define CONCAT22(a,b) ((u32)(((u32)(u16)(a)<<16)|(u16)(b)))
#define CONCAT24(a,b) ((u64)(((u64)(u16)(a)<<32)|(u32)(b)))
#define CONCAT31(a,b) ((u32)((((u32)(a)&0xffffff)<<8)|(u8)(b)))
#define CONCAT41(a,b) ((u64)(((u64)(u32)(a)<<8)|(u8)(b)))
#define CONCAT42(a,b) ((u64)(((u64)(u32)(a)<<16)|(u16)(b)))
#define CONCAT44(a,b) ((u64)(((u64)(u32)(a)<<32)|(u32)(b)))
#define CONCAT48(a,b) ((u64)(b))
#define CONCAT84(a,b) ((u64)(b))
#define CONCAT88(a,b) ((u64)(b))
#define SUB21(a,b) ((u8)((a)>>(8*(b))))
#define SUB41(a,b) ((u8)((a)>>(8*(b))))
#define SUB42(a,b) ((u16)((a)>>(8*(b))))
#define SUB81(a,b) ((u8)((u64)(a)>>(8*(b))))
#define SUB82(a,b) ((u16)((u64)(a)>>(8*(b))))
#define SUB84(a,b) ((u32)((u64)(a)>>(8*(b))))
#define ABS(x) ((x) < 0 ? -(x) : (x))
#define SQRT(x) ((f32)__builtin_sqrtf((f32)(x)))
#define ZEXT416(x) ((u64)(x))
static inline u32 LZCOUNT(u32 v) { u32 n = 0; if (v == 0) return 32; while (!(v & 0x80000000u)) { v <<= 1; n++; } return n; }
static inline u8 SBORROW4(s32 a, s32 b) { return ((a - b) ^ a) & (a ^ b) & 0x80000000u ? 1 : 0; }
static inline u8 CARRY4(u32 a, u32 b) { return (a + b) < a; }
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct ALLOCATOR;
struct YS_LIST_TASK_0;
struct kingdom_CONTEXT;
struct TASK_MANAGER;
struct Axa_CSJointT_Axa_FiberPS3;
struct CellFiberPpuContext;
struct Axa_FiberPS3;
struct Axa_CSJointT_Axa_ResourceEntry;
union TASK_ARGS;
struct YS_LIST_ELEM_TASK_1;
struct TASK;
struct TASK_THREAD;
struct YS_SLIST_ELEM_GAME_MODE_1;
struct GAME_MODE;

struct ALLOCATOR {  // class ALLOCATOR size=0x4
    void *_vptr_;                                      // +0x0
};

struct YS_LIST_TASK_0 {  // class YS::LIST<TASK, 0> size=0x8
    void *Head;                                        // +0x0
    void *Tail;                                        // +0x4
    operator u64() const { return *(const u64 *)this; }
    YS_LIST_TASK_0 &operator=(u64 v) { *(u64 *)this = v; return *this; }
};

struct kingdom_CONTEXT {  // class kingdom::CONTEXT size=0x10
    Axa_FiberPS3 *fiberHandle;                         // +0x0
    u32 dummy[3];                                      // +0x4
};

struct TASK_MANAGER {  // class TASK_MANAGER size=0x28
    ALLOCATOR super_ALLOCATOR;                         // +0x0
    ALLOCATOR *Allocator;                              // +0x4
    YS_LIST_TASK_0 TaskList;                           // +0x8
    u8 _pad0[224];
    TASK *Current;                                     // +0xf0
    kingdom_CONTEXT Context;                           // +0xf4
    u8 _pad1[12];
    TASK *Next;                                        // +0x110
};

struct Axa_CSJointT_Axa_FiberPS3 {  // class Axa::CSJointT<Axa::FiberPS3> size=0x8
    void *_vptr_;                                      // +0x0
    Axa_CSJointT_Axa_ResourceEntry *m_pNext;           // +0x4
};

struct CellFiberPpuContext {  // structure CellFiberPpuContext size=0x280
    u8 skip[640];                                      // +0x0
};

struct Axa_FiberPS3 {  // class Axa::FiberPS3 size=0x122c0
    Axa_CSJointT_Axa_FiberPS3 super_FiberPS3;          // +0x0
    u8 _pad0[8];
    CellFiberPpuContext context;                       // +0x10
    void *func;                                        // +0x290
    void *arg;                                         // +0x294
    u32 stackSize;                                     // +0x298
    s32 disposeFlg;                                    // +0x29c
    s32 dum[3];                                        // +0x2a0
    u32 _pad;                                          // +0x2ac
    u8 stack[73728];                                   // +0x2b0
    u32 _check[4];                                     // +0x122b0
};

struct Axa_CSJointT_Axa_ResourceEntry {  // class Axa::CSJointT<Axa::ResourceEntry> size=0x8
    void *_vptr_;                                      // +0x0
    Axa_CSJointT_Axa_ResourceEntry *m_pNext;           // +0x4
};

union TASK_ARGS {  // union TASK::ARGS size=0x4
    s32 i;
    s8 b;
    f32 f;
    void *p;
    operator u32() const { return *(const u32 *)this; }
    TASK_ARGS &operator=(u32 v) { *(u32 *)this = v; return *this; }
};

struct YS_LIST_ELEM_TASK_1 {  // class YS::LIST_ELEM<TASK, 1> size=0x8
    void *Next[1];                                     // +0x0
    void *Prev[1];                                     // +0x4
    operator u64() const { return *(const u64 *)this; }
    YS_LIST_ELEM_TASK_1 &operator=(u64 v) { *(u64 *)this = v; return *this; }
};

struct TASK {  // class TASK size=0x54
    void *EntryFunc;                                   // +0x0
    void *m_nThreadID;                                 // +0x4
    s32 m_nThreadSemaID;                               // +0x8
    s32 m_nSuspend;                                    // +0xc
    TASK_ARGS Args[8];                                 // +0x10
    TASK_MANAGER *Manager;                             // +0x30
    s32 Id;                                            // +0x34
    s32 Priority;                                      // +0x38
    void *Finalizer;                                   // +0x3c
    TASK_THREAD *Thread;                               // +0x40
    YS_LIST_ELEM_TASK_1 List;                          // +0x44
    TASK *Prev;                                        // +0x4c
    TASK *Next;                                        // +0x50
};

struct TASK_THREAD {  // structure TASK::THREAD size=0x20
    kingdom_CONTEXT Context;                           // +0x0
    s8 IsInit;                                         // +0x10
    u8 _pad0[3];
    s32 Wait;                                          // +0x14
    f32 GameWait;                                      // +0x18
    u32 StackSize;                                     // +0x1c
};

struct YS_SLIST_ELEM_GAME_MODE_1 {  // class YS::SLIST_ELEM<GAME_MODE, 1> size=0x4
    void *Next[1];                                     // +0x0
    operator u32() const { return *(const u32 *)this; }
    YS_SLIST_ELEM_GAME_MODE_1 &operator=(u32 v) { *(u32 *)this = v; return *this; }
};

struct GAME_MODE {  // class GAME_MODE size=0x2c
    void *_vptr_;                                      // +0x0
    TASK_MANAGER *TaskManager;                         // +0x4
    s8 ProfilerCode;                                   // +0x8
    u8 _pad0[3];
    YS_SLIST_ELEM_GAME_MODE_1 SList;                   // +0xc
    s32 Id;                                            // +0x10
    s32 TaskId;                                        // +0x14
    s32 TaskPriority;                                  // +0x18
    s32 State;                                         // +0x1c
    void *InitFunc;                                    // +0x20
    void *EnsureFunc;                                  // +0x24
    u32 StackSize;                                     // +0x28
};

typedef void (*TASK_FUNC)(TASK *);
extern "C" void * func_00103eb0() asm("_Z11getMenuModev");
extern "C" u8 func_00102a38(void *, TASK_FUNC) asm("func_00102a38");
extern "C" u32 D_00293b08 asm("D_00293b08");

// E3 0x00389e70 Tz::ChgMember::isExecChangeMember -> PS2 0x00293b70
u8 e3_00293b70() asm("_ZN2Tz9ChgMember18isExecChangeMemberEv");
u8 e3_00293b70()

{
  GAME_MODE *pGVar1;
  u8 bVar2;
  
                    /* Unresolved local var: u8 stat@[???] */
  pGVar1 = func_00103eb0();
  bVar2 = func_00102a38((TASK_MANAGER *)(u32)*(u32 *)(ZEXT48(pGVar1) + 4),(TASK_FUNC)((u32)&D_00293b08));
  return bVar2;
}

