// coverage: addr=0x002bc2e8 symbol=func_002bc2e8 size=108 class=branchy source=e3 status=exact fuzzy=100.0
// coverage-alternatives: m2c:near:99.26;lift:near:87.32;ghidra:near:82.15
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct Axa_FVECTOR4;
struct kn_FVector;
struct YS_SLIST_ELEM_SE3D_2;
struct YS_BITFLAG_4_u_int;
struct SE3D;

struct Axa_FVECTOR4 {  // structure Axa::FVECTOR4 size=0x10
    f32 x;                                             // +0x0
    f32 y;                                             // +0x4
    f32 z;                                             // +0x8
    f32 w;                                             // +0xc
};

struct kn_FVector {  // structure kn::FVector size=0x10
    Axa_FVECTOR4 super_FVECTOR4;                       // +0x0
};

struct YS_SLIST_ELEM_SE3D_2 {  // class YS::SLIST_ELEM<SE3D, 2> size=0x8
    void *Next[2];                                     // +0x0
};

struct YS_BITFLAG_4_u_int {  // class YS::BITFLAG<4, u_int> size=0x4
    u8 Flag[4];   // raw: klass[1] (size mismatch)     // +0x0
};

struct SE3D {  // class SE3D size=0x40
    kn_FVector m_pos;                                  // +0x0
    s32 m_num;                                         // +0x10
    s32 m_id;                                          // +0x14
    s32 m_bank;                                        // +0x18
    YS_SLIST_ELEM_SE3D_2 SList;                        // +0x1c
    YS_BITFLAG_4_u_int m_flag;                         // +0x24
    s16 m_volume;                                      // +0x28
    s16 m_minVolume;                                   // +0x2a
    s16 m_pan;                                         // +0x2c
    u8 _pad0[2];
    u16 m_polyId;                                      // +0x30
    u8 m_status;                                       // +0x32
    u8 m_type;                                         // +0x33
    u8 _pad1[14];
};

typedef u32 u_int;
extern "C" void * func_002bc158(int) asm("func_002bc158");
extern "C" void func_002bb310(int, int, int, u32) asm("func_002bb310");

// E3 0x00139f70 SOUND::createPolygonSe -> PS2 0x002bc2e8
u_int e3_002bc2e8(int seNum, int bank, int poly_id) asm("func_002bc2e8");
u_int e3_002bc2e8(int seNum, int bank, int poly_id)

{
  SE3D *pSVar1;
  u_int uVar2;
  
                    /* Unresolved local var: SE3D * se@[???] */
  pSVar1 = func_002bc158(seNum);
  if (pSVar1 == (SE3D *)0x0) {
    uVar2 = 0;
  }
  else {
    func_002bb310((SE3D *)ZEXT48(pSVar1),seNum,bank,poly_id);
    uVar2 = ((SE3D *)ZEXT48(pSVar1))->m_id;
  }
  return uVar2;
}

