// coverage: addr=0x002ba1b8 symbol=_ZN5SOUND11sebTransferEiii size=72 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: lift:near:98.22;ghidra:near:98.22;m2c:near:98.22
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF





extern "C" void func_002bc470(int) asm("func_002bc470");
extern "C" int func_002b6e24(int, int, int) asm("func_002b6e24");
extern "C" u32 e3g___LNst__ZN5SOUND11sebTransferEiii_0 asm("E3_UNMAPPED_007042f0");

// E3 0x0013acd0 SOUND::sebTransfer -> PS2 0x002ba1b8
void e3_002ba1b8(int bank, int adrs, int size) asm("_ZN5SOUND11sebTransferEiii");
void e3_002ba1b8(int bank, int adrs, int size)

{
  func_002bc470(bank);

  func_002b6e24(bank,adrs,size);
  return;
}

