// coverage: addr=0x002c5460 symbol=func_002c5460 size=36 class=straight source=e3 status=exact fuzzy=100.0
// coverage-alternatives: ghidra:exact:100.0;m2c:near:76.11;lift:near:11.11
#include "common/types.h"
typedef float f32; typedef double f64;
typedef u8 undefined; typedef u8 undefined1; typedef u16 undefined2; typedef u32 undefined4; typedef u64 undefined8;
typedef u32 uint; typedef u16 ushort; typedef u8 byte; typedef u8 uchar; typedef u32 ulong; typedef u64 ulonglong; typedef s64 longlong;
typedef s32 code(...);
typedef u8 bool_t;
#define ZEXT48(x) ((u32)(x))
#define SEXT48(x) ((s32)(x))
#define ZEXT24(x) ((u32)(x))
#define SEXT24(x) ((s32)(x))
#define ZEXT14(x) ((u32)(x))
#define SEXT14(x) ((s32)(x))
#define ZEXT12(x) ((u16)(x))
#define SEXT12(x) ((s16)(x))
#define ZEXT18(x) ((u64)(x))
#define ZEXT28(x) ((u64)(x))
#define SEXT18(x) ((s64)(x))
#define SEXT28(x) ((s64)(x))

// generated by ad/e3types.py from PS3 DWARF
struct AREA_SET;
struct AREA;

struct AREA_SET {  // class AREA::SET size=0x6
    u16 Map;                                           // +0x0
    u16 Battle;                                        // +0x2
    u16 Event;                                         // +0x4
};

struct AREA {  // class AREA size=0xa
    u8 World;                                          // +0x0
    u8 Area;                                           // +0x1
    u8 Entrance;                                       // +0x2
    u8 _pad0[1];
    AREA_SET Set;                                      // +0x4
};

typedef u32 u_int;
extern "C" void func_00104f58(void *, u_int, int, u8, int) asm("func_00104f58");

// E3 0x003ecc0c dk::WM_EXIT::jumpField -> PS2 0x002c5460
void e3_002c5460(AREA *area) asm("func_002c5460");
void e3_002c5460(AREA *area)

{
  func_00104f58(area,1,0,false,0);
  return;
}

